/*
 * ┌─────────────────────────────────────────────────────────────┐
 * │ IMPORTANT FOR AI AGENTS:                                    │
 * │ Do NOT edit this file directly.                             │
 * │ If changes are needed, ask the user for explicit permission │
 * │ and limit edits to the minimum required scope.              │
 * │ Alternatively, request that the user makes the edit.        │
 * └─────────────────────────────────────────────────────────────┘
 */
/*
 * ┌─────────────────────────────────────────────────────────────┐
 * │ IMPORTANT FOR AI AGENTS:                                    │
 * │ Do NOT edit this file directly.                             │
 * │ If changes are needed, ask the user for explicit permission │
 * │ and limit edits to the minimum required scope.              │
 * │ Alternatively, request that the user makes the edit.        │
 * └─────────────────────────────────────────────────────────────┘
 */
/*
 * ┌─────────────────────────────────────────────────────────────┐
 * │ IMPORTANT FOR AI AGENTS:                                    │
 * │ Do NOT edit this file directly.                             │
 * │ If changes are needed, ask the user for explicit permission │
 * │ and limit edits to the minimum required scope.              │
 * │ Alternatively, request that the user makes the edit.        │
 * └─────────────────────────────────────────────────────────────┘
 */
/**
 * tests/unit/server-ws.test.js
 * Section 1.1 — WebSocket Connection Management
 *
 * Tests the SW / Dashboard socket lifecycle:
 *   connects, initial messages, multi-client, disconnect, isolation.
 */

import { describe, test } from 'node:test';
import assert             from 'node:assert/strict';
import { withServer }     from '../helpers/server-fixture.js';
import {
  WSClient,
  createSWClient,
  createDashboardClient,
  waitEvent,
  sleep,
} from '../helpers/ws-client.js';
import { createPortPool } from '../helpers/port-pool.js';

const ports = createPortPool(0); // file ID 0 → ports 18000–18099

// ── Helper ────────────────────────────────────────────────────────────────────

async function setup() {
  const { server, teardown } = await withServer(ports.next());
  return { server, teardown };
}

// ══════════════════════════════════════════════════════════════════════════════
describe('1.1 WebSocket Connection Management', () => {

  // ── SW connect ─────────────────────────────────────────────────────────────

  test('SW connects → swSockets.size === 1 and SET_CONFIG sent', async () => {
    const { server, teardown } = await setup();
    try {
      const sw = new WSClient(`${server.wsUrl}?sw=1`);
      await sw.connect();

      const msg = await sw.nextMessage();
      assert.strictEqual(server.swSockets.size, 1, 'exactly one SW socket');
      assert.strictEqual(msg.type, 'SET_CONFIG', 'handshake must be SET_CONFIG');
      assert.ok(msg.config !== undefined, 'SET_CONFIG must include config key');

      await sw.close();
    } finally {
      await teardown();
    }
  });

  test('SW SET_CONFIG config is an object (not null, not array)', async () => {
    const { server, teardown } = await setup();
    try {
      const sw = new WSClient(`${server.wsUrl}?sw=1`);
      await sw.connect();
      const { config } = await sw.nextMessage();

      assert.ok(config !== null && typeof config === 'object' && !Array.isArray(config));
      await sw.close();
    } finally {
      await teardown();
    }
  });

  // ── Dashboard connect ───────────────────────────────────────────────────────

  test('Dashboard connects → dashboardSockets.size === 1 and INIT sent', async () => {
    const { server, teardown } = await setup();
    try {
      const dash = new WSClient(server.wsUrl);  // no ?sw=1
      await dash.connect();

      const msg = await dash.nextMessage();
      assert.strictEqual(server.dashboardSockets.size, 1, 'exactly one dashboard socket');
      assert.strictEqual(msg.type, 'INIT', 'handshake must be INIT');
      assert.ok(Array.isArray(msg.sessions), 'INIT.sessions must be an array');

      await dash.close();
    } finally {
      await teardown();
    }
  });

  test('Dashboard INIT does not include SW sockets count or credentials', async () => {
    const { server, teardown } = await setup();
    try {
      const dash = await createDashboardClient(server);
      // INIT should expose sessions, not raw internal state
      const init = server.dashboardSockets.size; // ensure 1
      assert.strictEqual(init, 1);
      await dash.close();
    } finally {
      await teardown();
    }
  });

  // ── Multiple SWs ────────────────────────────────────────────────────────────

  test('Two SWs connect → both in swSockets, both receive broadcastToSW', async () => {
    const { server, teardown } = await setup();
    try {
      const sw1 = await createSWClient(server);
      const sw2 = await createSWClient(server);

      assert.strictEqual(server.swSockets.size, 2, 'both SWs in set');

      const p1 = sw1.nextMessage(m => m.type === 'TEST_BROADCAST');
      const p2 = sw2.nextMessage(m => m.type === 'TEST_BROADCAST');

      server.broadcastToSW({ type: 'TEST_BROADCAST', seq: 1 });

      const [m1, m2] = await Promise.all([p1, p2]);
      assert.strictEqual(m1.type, 'TEST_BROADCAST');
      assert.strictEqual(m2.type, 'TEST_BROADCAST');
      assert.strictEqual(m1.seq, 1);
      assert.strictEqual(m2.seq, 1);

      await sw1.close();
      await sw2.close();
    } finally {
      await teardown();
    }
  });

  test('Two SWs — no cross-tab data leak (each gets same broadcast, not each other\'s data)', async () => {
    const { server, teardown } = await setup();
    try {
      const sw1 = await createSWClient(server);
      const sw2 = await createSWClient(server);

      // Send unique SET_CONFIG per SW — this tests that server distinguishes them
      const sentIds = new Set();
      for (const ws of server.swSockets) {
        const id = Math.random().toString(36).slice(2);
        sentIds.add(id);
        ws.send(JSON.stringify({ type: 'ECHO_ID', id }));
      }

      // Verify each SW only received its own message (server routes by ws reference)
      const msgs1 = await sw1.collect(100);
      const msgs2 = await sw2.collect(100);

      // No message from sw1's set should appear in sw2's received queue
      const ids1 = msgs1.map(m => m.id).filter(Boolean);
      const ids2 = msgs2.map(m => m.id).filter(Boolean);
      // They should have different ids (no overlap from being each other's target)
      const overlap = ids1.filter(id => ids2.includes(id));
      assert.strictEqual(overlap.length, 0, 'no cross-tab data leak');

      await sw1.close();
      await sw2.close();
    } finally {
      await teardown();
    }
  });

  // ── SW disconnect ───────────────────────────────────────────────────────────

  test('SW disconnects → swSockets.size === 0, sw:disconnect event emitted', async () => {
    const { server, teardown } = await setup();
    try {
      const sw = await createSWClient(server);
      assert.strictEqual(server.swSockets.size, 1);

      const disconnectP = waitEvent(server, 'sw:disconnect');
      await sw.close();
      await disconnectP;

      assert.strictEqual(server.swSockets.size, 0, 'socket set must be empty');
    } finally {
      await teardown();
    }
  });

  test('SW disconnect → no crash when dashboard tries to receive', async () => {
    const { server, teardown } = await setup();
    try {
      const sw   = await createSWClient(server);
      const dash = await createDashboardClient(server);

      await sw.close();
      await waitEvent(server, 'sw:disconnect');

      // Server must not crash when broadcasting to empty SW set
      assert.doesNotThrow(() => server.broadcastToSW({ type: 'NOP' }));
      // Dashboard must still be connected
      assert.strictEqual(server.dashboardSockets.size, 1);

      await dash.close();
    } finally {
      await teardown();
    }
  });

  // ── Dashboard disconnect ────────────────────────────────────────────────────

  test('Dashboard disconnects → dashboardSockets.size === 0, dashboard:disconnect emitted', async () => {
    const { server, teardown } = await setup();
    try {
      const dash = await createDashboardClient(server);
      assert.strictEqual(server.dashboardSockets.size, 1);

      const disconnectP = waitEvent(server, 'dashboard:disconnect');
      await dash.close();
      await disconnectP;

      assert.strictEqual(server.dashboardSockets.size, 0);
    } finally {
      await teardown();
    }
  });

  test('Dashboard disconnects → SW connection unaffected', async () => {
    const { server, teardown } = await setup();
    try {
      const sw   = await createSWClient(server);
      const dash = await createDashboardClient(server);

      const disconnectP = waitEvent(server, 'dashboard:disconnect');
      await dash.close();
      await disconnectP;

      assert.strictEqual(server.swSockets.size, 1, 'SW must still be connected');

      await sw.close();
    } finally {
      await teardown();
    }
  });

  // ── Mixed disconnect ────────────────────────────────────────────────────────

  test('Mixed: SW disconnects, dashboard stays → no stale data delivered to dashboard', async () => {
    const { server, teardown } = await setup();
    try {
      const sw   = await createSWClient(server);
      const dash = await createDashboardClient(server);

      await sw.close();
      await waitEvent(server, 'sw:disconnect');

      // Server must not forward anything to dashboard when SW disconnects
      const strayMsgs = await dash.collect(150);
      assert.strictEqual(strayMsgs.length, 0, 'no stale data delivered after SW disconnect');

      assert.strictEqual(server.dashboardSockets.size, 1);

      await dash.close();
    } finally {
      await teardown();
    }
  });

  // ── Rapid reconnect ─────────────────────────────────────────────────────────

  test('Rapid SW reconnect (5×) → no crash, set always consistent', async () => {
    const { server, teardown } = await setup();
    try {
      for (let i = 0; i < 5; i++) {
        const sw = await createSWClient(server);
        assert.strictEqual(server.swSockets.size, 1, `iteration ${i}: expected 1 SW`);
        await sw.close();
        await waitEvent(server, 'sw:disconnect', 500).catch(() => {});
        // Brief pause to let close propagate
        await sleep(10);
      }
      assert.strictEqual(server.swSockets.size, 0, 'all sockets cleaned up after reconnects');
    } finally {
      await teardown();
    }
  });

  // ── Broadcast isolation ─────────────────────────────────────────────────────

  test('broadcastToDashboard does not reach SW sockets', async () => {
    const { server, teardown } = await setup();
    try {
      const sw   = await createSWClient(server);
      const dash = await createDashboardClient(server);

      const dashPromise = dash.nextMessage(m => m.type === 'DASH_ONLY', 1_000);
      server.broadcastToDashboard({ type: 'DASH_ONLY' });

      const dashMsg = await dashPromise;
      assert.strictEqual(dashMsg.type, 'DASH_ONLY');

      // SW must not have received this
      const swMsgs = await sw.collect(100);
      assert.ok(
        !swMsgs.some(m => m.type === 'DASH_ONLY'),
        'SW must not receive dashboard broadcasts'
      );

      await sw.close();
      await dash.close();
    } finally {
      await teardown();
    }
  });

  test('broadcastToSW does not reach Dashboard sockets', async () => {
    const { server, teardown } = await setup();
    try {
      const sw   = await createSWClient(server);
      const dash = await createDashboardClient(server);

      const swPromise = sw.nextMessage(m => m.type === 'SW_ONLY', 1_000);
      server.broadcastToSW({ type: 'SW_ONLY' });

      await swPromise;

      const dashMsgs = await dash.collect(100);
      assert.ok(
        !dashMsgs.some(m => m.type === 'SW_ONLY'),
        'Dashboard must not receive SW-targeted broadcasts'
      );

      await sw.close();
      await dash.close();
    } finally {
      await teardown();
    }
  });
});
